### ISSUE TITLE
Issue with Installing using the script

### ISSUE THREAD

**Issue by product-noob** [monfresh/install-ruby-on-macos#2]
Ran the
```
 cd ~
curl --remote-name https://raw.githubusercontent.com/monfresh/install-ruby-on-macos/master/install-ruby
/usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log 
```  script. Gave the below error:

```
generating x86_64-darwin18-fake.rb
x86_64-darwin18-fake.rb updated
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-darwin18-fake ./tool/rbinstall.rb --make="/Library/Developer/CommandLineTools/usr/bin/make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --rdoc-output=".ext/rdoc" --html-output=".ext/html"
installing binary commands:         /Users/prince/.rubies/ruby-2.7.2/bin
installing base libraries:          /Users/prince/.rubies/ruby-2.7.2/lib
installing arch files:              /Users/prince/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-darwin18
installing extension objects:       /Users/prince/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-darwin18
installing extension objects:       /Users/prince/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/x86_64-darwin18
installing extension objects:       /Users/prince/.rubies/ruby-2.7.2/lib/ruby/vendor_ruby/2.7.0/x86_64-darwin18
installing extension headers:       /Users/prince/.rubies/ruby-2.7.2/include/ruby-2.7.0/x86_64-darwin18
installing extension scripts:       /Users/prince/.rubies/ruby-2.7.2/lib/ruby/2.7.0
installing extension scripts:       /Users/prince/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0
installing extension scripts:       /Users/prince/.rubies/ruby-2.7.2/lib/ruby/vendor_ruby/2.7.0
installing extension headers:       /Users/prince/.rubies/ruby-2.7.2/include/ruby-2.7.0/ruby
installing rdoc:                    /Users/prince/.rubies/ruby-2.7.2/share/ri/2.7.0/system
installing html-docs:               /Users/prince/.rubies/ruby-2.7.2/share/doc/ruby
installing capi-docs:               /Users/prince/.rubies/ruby-2.7.2/share/doc/ruby
installing command scripts:         /Users/prince/.rubies/ruby-2.7.2/bin
installing library scripts:         /Users/prince/.rubies/ruby-2.7.2/lib/ruby/2.7.0
installing common headers:          /Users/prince/.rubies/ruby-2.7.2/include/ruby-2.7.0
installing manpages:                /Users/prince/.rubies/ruby-2.7.2/share/man (man1, man5)
installing default gems from lib:   /Users/prince/.rubies/ruby-2.7.2/lib/ruby/gems/2.7.0 (build_info, cache, doc, extensions, gems, specifications)
                                    benchmark 0.1.0
/Users/prince/src/ruby-2.7.2/lib/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- openssl (LoadError)
	from /Users/prince/src/ruby-2.7.2/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /Users/prince/src/ruby-2.7.2/lib/rubygems/specification.rb:2430:in `to_ruby'
	from ./tool/rbinstall.rb:846:in `block (2 levels) in install_default_gem'
	from ./tool/rbinstall.rb:279:in `open_for_install'
	from ./tool/rbinstall.rb:845:in `block in install_default_gem'
	from ./tool/rbinstall.rb:835:in `each'
	from ./tool/rbinstall.rb:835:in `install_default_gem'
	from ./tool/rbinstall.rb:799:in `block in <main>'
	from ./tool/rbinstall.rb:950:in `block in <main>'
	from ./tool/rbinstall.rb:947:in `each'
	from ./tool/rbinstall.rb:947:in `<main>'
make: *** [do-install-all] Error 1
!!! Installation of ruby 2.7.2 failed!
failed

```

**Comment by monfresh** [comment]
Hi. I'm sorry you're running into issues running the script. Could you please paste the entire contents of the file called `laptop.log` in your macOS Home folder? Also, what model of Mac computer are you running this on, and on what version of macOS?

**Comment by mateforlife** [comment]
I have the same error:  
`
Welcome to the Ruby installation script!

You should be and up and running with a working Ruby environment in a few minutes.

The following lines are to help me debug any issues:

Current shell: /bin/zsh.

macOS version:
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

Mac model:
hw.model: MacBookPro16,1

Homebrew already installed. Skipping ...

Verifying the Homebrew installation...
Your system is ready to brew.

Your Homebrew installation is good to go.
Warning: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead.
Using chruby
Using ruby-install
Homebrew Bundle complete! 2 Brewfile dependencies now installed.

Checking if a newer version of Ruby is available...

You have the latest version of Ruby

Updating Rubygems...
ERROR:  Loading command: update (LoadError)
	cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
failed

`

**Comment by monfresh** [comment]
Hi @mateforlife. I see that you are running an older version of Catalina. Please make sure you have the latest software updates installed. Go to System Preferences, then Software Update, and install any Catalina updates (not Big Sur). The updates should automatically restart your computer, but if they don't, restart your computer, then try the script again.

**Comment by product-noob** [comment]
Hey @monfresh , Appreciate such a quick revert. 
Attaching the laptop.log file here.
[laptop.log](https://github.com/monfresh/install-ruby-on-macos/files/5711236/laptop.log)

**Comment by monfresh** [comment]
Hi @product-noob. If you look at the top of the laptop.log file, you will see this message from Homebrew:
```
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```
Please follow these steps here:
https://github.com/monfresh/laptop/issues/63#issuecomment-746446876

**Comment by mateforlife** [comment]
@monfresh the next version to install is Big Sur, here is not other updates :(

**Comment by monfresh** [comment]
@mateforlife Can you please send me a screenshot of your Software Update screen? You can select just that specific window by pressing `shift-command-4-spacebar` and then place your cursor over the Software Update screen and then click the trackpad to take the screenshot. It should be saved to your Desktop.

**Comment by product-noob** [comment]
Thanks again @monfresh, cheking this one now now.

**Comment by product-noob** [comment]
Also here's step by step of what I did:

1. Ran brew doctor
Got Warning: 
```
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```
2. Ran these lines of codes (from stackoverflow) to correct it:
```
export PATH="/usr/local/bin:$PATH"
source ~/.bash_profile

```
3. Ran softwareupdate --all --install --force
`Software Update Tool

Finding available software
No updates are available.`

**Comment by mateforlife** [comment]
![image](https://user-images.githubusercontent.com/31286850/102533903-c3d04880-4084-11eb-9d80-b8b50182ccda.png)

**Comment by jeremiah-shore** [comment]
Interesting you would be troubleshooting so recently to my issues. I'm having a very similar problem. My difference is that I got the install failed message, BUT restarting terminal and running `ruby -v` yields `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`. `which ruby` also returns `/Users/jeremiah/.rubies/ruby-2.7.2/bin/ruby`, so the install looks ok. 

My problem is that when I try to install a gem, I get the following:
```
ERROR:  Loading command: install (LoadError)
	cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

Let me know if there is anything else you need to troubleshoot. I've no experience with ruby, and I'm only doing this to use a specific gem called `wayback_machine_downloader`. Thanks in advance for any help you can offer!

**Comment by monfresh** [comment]
Thanks everyone for reporting this. I just uninstalled an older version of Ruby that I don't use and tried reinstalling it and I'm seeing the same `openssl` issue. Something must have changed in the past few days. I will do some research and post an update when I figure it out.

**Comment by monfresh** [comment]
This seems to be an issue with `ruby-install`. I'm not sure why it's not working anymore all of a sudden. When I tried installing Ruby with `asdf`, it worked fine. I opened an issue on the `ruby-install` repo. In the meantime, I will do some more testing with `asdf` and maybe I will update the script to use it instead of `chruby` and `ruby-install`.

**Comment by monfresh** [comment]
I verified that there is indeed a bug with the latest version of `ruby-install`. It's not properly setting certain parameters related to OpenSSL. I updated my issue with all the details if anyone is interested: https://github.com/postmodern/ruby-install/issues/387

Homebrew does not make it easy to install older versions of tools, so I'm trying to figure out if the best way to deal with this while the `ruby-install` maintainer fixes it. Maybe he can remove the latest version from Homebrew and push the older one until he fixes it.

**Comment by monfresh** [comment]
I think I found a solution. Stay tuned!

**Comment by monfresh** [comment]
@jeremiah-shore @mateforlife @product-noob  Could you please try this?

1. Run `sudo rm -rf ~/.rubies/ruby-2.7.2`
2. Then run the script again: 
```sh
cd ~
curl --remote-name https://raw.githubusercontent.com/monfresh/install-ruby-on-macos/master/install-ruby
/usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log
```

**Comment by jeremiah-shore** [comment]
Performed the recommended steps, but ran into issues with the script...

```
Jeremiahs-MacBook-Pro~(:|✔) % /usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log


Welcome to the Ruby installation script!

You should be and up and running with a working Ruby environment in a few minutes.

The following lines are to help me debug any issues:

Current shell: /bin/zsh.

macOS version:
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114

Mac model:
hw.model: MacBookPro15,1

Homebrew already installed. Skipping ...

Verifying the Homebrew installation...
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Your Homebrew installation reported some errors or warnings.
Review the Homebrew messages to see if any action is needed.
Error: 
  homebrew-core is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI systems (which should instead be fixed to not use shallow clones). Sorry for
the inconvenience!
Using chruby
Using ruby-install
Homebrew Bundle complete! 2 Brewfile dependencies now installed.

Checking if a newer version of Ruby is available...
chruby: unknown Ruby: ruby-
failed
```

I'll try some of the remedial steps provided in the output and report back if anything changes. Note; my system info shows no updates available other than the Big Sur upgrade.

**Comment by jeremiah-shore** [comment]
So I was able to update with the manual recommendation, as well as resolving the issue with homebrew through the suggested fix. However, the install still appears to fail. Here's my output...

```
Jeremiahs-MacBook-Pro~(:|✔) % /usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log


Welcome to the Ruby installation script!

You should be and up and running with a working Ruby environment in a few minutes.

The following lines are to help me debug any issues:

Current shell: /bin/zsh.

macOS version:
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114

Mac model:
hw.model: MacBookPro15,1

Homebrew already installed. Skipping ...

Verifying the Homebrew installation...
Your system is ready to brew.

Your Homebrew installation is good to go.
Using chruby
Using ruby-install
Homebrew Bundle complete! 2 Brewfile dependencies now installed.

Checking if a newer version of Ruby is available...
chruby: unknown Ruby: ruby-
failed
```

**Comment by monfresh** [comment]
Ah! I didn't test the scenario where no Ruby versions were installed, but chruby and ruby-install were already installed. I just pushed a fix. One more time with feeling!
```shell
curl --remote-name https://raw.githubusercontent.com/monfresh/install-ruby-on-macos/master/install-ruby
/usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log
```

**Comment by product-noob** [comment]
Still unable to install using the script. Am I doing something wrong here 😞 
[laptop.log](https://github.com/monfresh/install-ruby-on-macos/files/5720819/laptop.log)

**Comment by monfresh** [comment]
@product-noob Your previous installation of Ruby was faulty, so you have to remove it first, then run the script again. Please try these steps:

1. Run `rm -rf ~/.rubies/ruby-2.7.2`
If it says "permission denied", try it with `sudo`:
```shell
sudo rm -rf ~/.rubies/ruby-2.7.2
```

2. Then run the script again: 
```sh
cd ~
curl --remote-name https://raw.githubusercontent.com/monfresh/install-ruby-on-macos/master/install-ruby
/usr/bin/env bash install-ruby 2>&1 | tee ~/laptop.log
```

**Comment by product-noob** [comment]
It worked this time like a charm! @monfresh Many thanks!! 👍
